#!/usr/bin/env python3
"""AP2 product split: Debug is the sample app, Release is the static library.

Run from the repo root:

    python ap2_product.py                  # Debug  -> build/bin/Debug/ap2.exe
    python ap2_product.py --config Release # Release -> build/lib/Release/libap2.a

`--emit-cmake` is for the cforge/CMake hook. You do not need it by hand.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Sequence, TextIO


ROOT: Path = Path(__file__).resolve().parent
BUILD_DIR: Path = ROOT / "build"
CORE_DIR: Path = ROOT / "src" / "core"

APP_TARGET: str = "ap2_app"
LIB_TARGET: str = "ap2_lib"
PHONY_TARGET: str = "ap2"


def _lib_sources() -> list[str]:
    paths: list[Path] = sorted(CORE_DIR.glob("*.c"))
    if not paths:
        raise SystemExit(f"AP2: no sources in {CORE_DIR}")
    return [path.relative_to(ROOT).as_posix() for path in paths]


def _write_product_cmake(out: TextIO, sources: Sequence[str]) -> None:
    source_list: str = "\n  ".join(
        f"${{CMAKE_CURRENT_SOURCE_DIR}}/{source}" for source in sources
    )
    out.write(
        f"""# Generated by ap2_product.py. Do not edit.
# Debug: sample executable. Any other config: static library.

if(NOT TARGET {APP_TARGET})
  message(FATAL_ERROR
    "AP2: expected executable target `{APP_TARGET}`. "
    "inject_before_target must rename PROJECT_NAME before add_executable.")
endif()

set(_AP2_LIB_SOURCES
  {source_list}
)

if(NOT TARGET {LIB_TARGET})
  add_library({LIB_TARGET} STATIC ${{_AP2_LIB_SOURCES}})
endif()

set_target_properties({APP_TARGET} PROPERTIES
  OUTPUT_NAME "$<$<CONFIG:Debug>:ap2>$<$<NOT:$<CONFIG:Debug>>:ap2_app>"
  EXCLUDE_FROM_ALL TRUE
)
set_target_properties({LIB_TARGET} PROPERTIES
  OUTPUT_NAME ap2
  EXCLUDE_FROM_ALL TRUE
)

target_include_directories({LIB_TARGET} PUBLIC
  "${{CMAKE_CURRENT_SOURCE_DIR}}/include"
  "${{CMAKE_CURRENT_SOURCE_DIR}}/third_party/stb"
  "${{CMAKE_CURRENT_SOURCE_DIR}}/third_party/miniaudio")

get_target_property(_ap2_iface_defs {APP_TARGET} INTERFACE_COMPILE_DEFINITIONS)
if(_ap2_iface_defs)
  target_compile_definitions({LIB_TARGET} PUBLIC ${{_ap2_iface_defs}})
endif()

get_target_property(_ap2_defs {APP_TARGET} COMPILE_DEFINITIONS)
if(_ap2_defs)
  target_compile_definitions({LIB_TARGET} PUBLIC ${{_ap2_defs}})
endif()

target_link_libraries({LIB_TARGET} PUBLIC glad glfw)
if(WIN32)
  target_link_libraries({LIB_TARGET} PUBLIC user32 kernel32 opengl32 gdi32)
elseif(APPLE)
else()
  target_link_libraries({LIB_TARGET} PUBLIC GL dl m pthread)
endif()

if(NOT TARGET {PHONY_TARGET})
  add_custom_command(
    OUTPUT "${{CMAKE_BINARY_DIR}}/ap2-$<CONFIG>.stamp"
    COMMAND "${{CMAKE_COMMAND}}" -E touch
            "${{CMAKE_BINARY_DIR}}/ap2-$<CONFIG>.stamp"
    DEPENDS $<IF:$<CONFIG:Debug>,{APP_TARGET},{LIB_TARGET}>
    VERBATIM
    COMMENT "AP2 $<CONFIG> product"
  )
  add_custom_target({PHONY_TARGET} ALL
    DEPENDS "${{CMAKE_BINARY_DIR}}/ap2-$<CONFIG>.stamp")
endif()
"""
    )


def emit_cmake(out_path: Path) -> int:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8", newline="\n") as handle:
        _write_product_cmake(handle, _lib_sources())
    return 0


def _which(name: str) -> str | None:
    found: str | None = shutil.which(name)
    return found


def _ensure_configured(config: str) -> None:
    cache: Path = BUILD_DIR / "CMakeCache.txt"
    if cache.exists():
        return
    cforge: str | None = _which("cforge")
    if cforge is None:
        raise SystemExit("AP2: no build/ yet, and cforge is not on PATH")
    result: subprocess.CompletedProcess[str] = subprocess.run(
        [cforge, "build", "-c", config],
        cwd=ROOT,
        check=False,
    )
    if result.returncode != 0:
        raise SystemExit(result.returncode)


def build_product(config: str) -> int:
    _ensure_configured(config)
    cmake: str | None = _which("cmake")
    if cmake is None:
        raise SystemExit("AP2: cmake is not on PATH")
    is_debug: bool = config.lower() == "debug"
    target: str = APP_TARGET if is_debug else LIB_TARGET
    command: list[str] = [
        cmake,
        "--build",
        str(BUILD_DIR),
        "--config",
        config,
        "--target",
        target,
    ]
    print(f"AP2: {config} -> {target}", flush=True)
    result: subprocess.CompletedProcess[str] = subprocess.run(
        command, cwd=ROOT, check=False
    )
    if result.returncode != 0:
        return result.returncode
    if is_debug:
        exe: Path = BUILD_DIR / "bin" / config / "ap2.exe"
        alt: Path = BUILD_DIR / "bin" / config / "ap2"
        print(f"AP2: app  {exe if exe.exists() else alt}")
    else:
        archive: Path = BUILD_DIR / "lib" / config / "libap2.a"
        print(f"AP2: lib  {archive}")
    return 0


def _parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        description="Build AP2 as a Debug app or a Release static library.",
    )
    parser.add_argument(
        "--config",
        "-c",
        default="Debug",
        help="Debug (sample app) or Release (static library)",
    )
    parser.add_argument(
        "--emit-cmake",
        action="store_true",
        help="Write the CMake fragment instead of building",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="With --emit-cmake, path to write",
    )
    parser.add_argument(
        "--source-dir",
        type=Path,
        default=ROOT,
        help=argparse.SUPPRESS,
    )
    parser.add_argument("--app-target", default=APP_TARGET, help=argparse.SUPPRESS)
    parser.add_argument("--lib-target", default=LIB_TARGET, help=argparse.SUPPRESS)
    parser.add_argument("--phony-target", default=PHONY_TARGET, help=argparse.SUPPRESS)
    return parser.parse_args(list(argv))


def main(argv: Sequence[str]) -> int:
    args: argparse.Namespace = _parse_args(argv)
    if args.emit_cmake:
        out_path: Path = args.out if args.out is not None else BUILD_DIR / "ap2-product-gen.cmake"
        return emit_cmake(out_path)
    config: str = str(args.config)
    if config.lower() == "debug":
        config = "Debug"
    elif config.lower() == "release":
        config = "Release"
    return build_product(config)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
