#!/usr/bin/env python3
"""Emit CMake that makes Debug an app and Release a static library.

cforge always runs `cmake --build --target ap2`. The generated CMakeLists
creates an executable under whatever ${PROJECT_NAME} is at add_executable
time. cforge.toml renames that to ap2_app, then this script writes a
custom target named `ap2` that depends on the app in Debug and the
library otherwise.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence, TextIO


def _lib_sources(source_dir: Path) -> list[str]:
    core_dir: Path = source_dir / "src" / "core"
    paths: list[Path] = sorted(core_dir.glob("*.c"))
    if not paths:
        raise SystemExit(f"AP2: no sources in {core_dir}")
    return [path.relative_to(source_dir).as_posix() for path in paths]


def _write_product_cmake(
    out: TextIO,
    *,
    sources: Sequence[str],
    app_target: str,
    lib_target: str,
    phony_target: str,
) -> None:
    source_list: str = "\n  ".join(
        f"${{CMAKE_CURRENT_SOURCE_DIR}}/{source}" for source in sources
    )
    out.write(
        f"""# Generated by cmake/ap2_product.py. Do not edit.
# Debug: sample executable. Any other config: static library.

if(NOT TARGET {app_target})
  message(FATAL_ERROR
    "AP2: expected executable target `{app_target}`. "
    "inject_before_target must rename PROJECT_NAME before add_executable.")
endif()

set(_AP2_LIB_SOURCES
  {source_list}
)

if(NOT TARGET {lib_target})
  add_library({lib_target} STATIC ${{_AP2_LIB_SOURCES}})
endif()

set_target_properties({app_target} PROPERTIES
  OUTPUT_NAME ap2
  EXCLUDE_FROM_ALL TRUE
)
set_target_properties({lib_target} PROPERTIES
  OUTPUT_NAME ap2
  EXCLUDE_FROM_ALL TRUE
)

get_target_property(_ap2_inc {app_target} INTERFACE_INCLUDE_DIRECTORIES)
if(_ap2_inc)
  target_include_directories({lib_target} PUBLIC ${{_ap2_inc}})
else()
  target_include_directories({lib_target} PUBLIC
    "${{CMAKE_CURRENT_SOURCE_DIR}}/include"
    "${{CMAKE_CURRENT_SOURCE_DIR}}/third_party/stb"
    "${{CMAKE_CURRENT_SOURCE_DIR}}/third_party/miniaudio")
endif()

get_target_property(_ap2_iface_defs {app_target} INTERFACE_COMPILE_DEFINITIONS)
if(_ap2_iface_defs)
  target_compile_definitions({lib_target} PUBLIC ${{_ap2_iface_defs}})
endif()

get_target_property(_ap2_defs {app_target} COMPILE_DEFINITIONS)
if(_ap2_defs)
  target_compile_definitions({lib_target} PUBLIC ${{_ap2_defs}})
endif()

get_target_property(_ap2_opts {app_target} COMPILE_OPTIONS)
if(_ap2_opts)
  target_compile_options({lib_target} PRIVATE ${{_ap2_opts}})
endif()

get_target_property(_ap2_libs {app_target} INTERFACE_LINK_LIBRARIES)
if(NOT _ap2_libs)
  get_target_property(_ap2_libs {app_target} LINK_LIBRARIES)
endif()
if(_ap2_libs)
  target_link_libraries({lib_target} PUBLIC ${{_ap2_libs}})
endif()

if(NOT TARGET {phony_target})
  add_custom_target({phony_target} ALL
    DEPENDS $<IF:$<CONFIG:Debug>,{app_target},{lib_target}>)
endif()
"""
    )


def _parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        description=__doc__,
    )
    parser.add_argument(
        "--source-dir",
        type=Path,
        required=True,
        help="Project root (contains src/core)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        required=True,
        help="Path to write the generated CMake fragment",
    )
    parser.add_argument("--app-target", default="ap2_app")
    parser.add_argument("--lib-target", default="ap2_lib")
    parser.add_argument("--phony-target", default="ap2")
    return parser.parse_args(list(argv))


def main(argv: Sequence[str]) -> int:
    args: argparse.Namespace = _parse_args(argv)
    source_dir: Path = args.source_dir.resolve()
    out_path: Path = args.out
    out_path.parent.mkdir(parents=True, exist_ok=True)
    sources: list[str] = _lib_sources(source_dir)
    with out_path.open("w", encoding="utf-8", newline="\n") as handle:
        _write_product_cmake(
            handle,
            sources=sources,
            app_target=str(args.app_target),
            lib_target=str(args.lib_target),
            phony_target=str(args.phony_target),
        )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
